# Generated by Django 3.0.8 on 2020-08-06 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoQR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=45)),
                ('Imagen', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=45)),
                ('Apellido', models.CharField(max_length=45)),
                ('Telefono', models.CharField(max_length=45)),
                ('DNI', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=45)),
                ('Peso', models.CharField(max_length=45)),
                ('Descripcion', models.CharField(max_length=45)),
                ('Pago', models.CharField(max_length=45)),
                ('Estado', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Movilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Conductor', models.CharField(max_length=45)),
                ('Marca', models.CharField(max_length=45)),
                ('Placa', models.CharField(max_length=45)),
                ('Certificado', models.CharField(max_length=45)),
                ('Licencia', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Remitente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=45)),
                ('Apellido', models.CharField(max_length=45)),
                ('Telefono', models.CharField(max_length=45)),
                ('DNI', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='GuiaRemision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sucursal', models.CharField(max_length=45)),
                ('Partida', models.CharField(max_length=45)),
                ('Llegada', models.CharField(max_length=45)),
                ('Fecha', models.DateField()),
                ('CodigoQR', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='GestionDeCargas.CodigoQR')),
            ],
        ),
        migrations.AddField(
            model_name='codigoqr',
            name='Destinatario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='GestionDeCargas.Destinatario'),
        ),
        migrations.AddField(
            model_name='codigoqr',
            name='Encomienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='GestionDeCargas.Encomienda'),
        ),
        migrations.AddField(
            model_name='codigoqr',
            name='Movilidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='GestionDeCargas.Movilidad'),
        ),
        migrations.AddField(
            model_name='codigoqr',
            name='Remitente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='GestionDeCargas.Remitente'),
        ),
    ]
