# Generated by Django 3.0.8 on 2020-08-08 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeCargas', '0002_auto_20200806_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guiaremision',
            name='CodigoQR',
        ),
        migrations.AddField(
            model_name='guiaremision',
            name='Destinatario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='GestionDeCargas.Destinatario'),
        ),
        migrations.AddField(
            model_name='guiaremision',
            name='Encomienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='GestionDeCargas.Encomienda'),
        ),
        migrations.AddField(
            model_name='guiaremision',
            name='Movilidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='GestionDeCargas.Movilidad'),
        ),
        migrations.AddField(
            model_name='guiaremision',
            name='Remitente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='GestionDeCargas.Remitente'),
        ),
        migrations.DeleteModel(
            name='CodigoQR',
        ),
    ]
